/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2016-05-03 08:07:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Res.JSP.User;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.DAO.*;

public final class userhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");

   // Set refresh, autoload time as 5 seconds
   response.setIntHeader("Refresh", 60);
   // Get current time
   Calendar calendar = new GregorianCalendar();
   String am_pm;
   int hour = calendar.get(Calendar.HOUR);
   int minute = calendar.get(Calendar.MINUTE);
   int second = calendar.get(Calendar.SECOND);
   if(calendar.get(Calendar.AM_PM) == 0)
      am_pm = "AM";
   else
      am_pm = "PM";
   String CT = hour+":"+ minute +":"+ second +" "+ am_pm;
   //out.println("Current Time: " + CT + "\n");

      out.write("\r\n");
      out.write("\r\n");

HttpSession hs = request.getSession();
String userid=hs.getAttribute("name").toString();

System.out.println("User ID------------ ;"+userid);

hs.setAttribute("userid",userid);
String sessionid=hs.getId();


      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/Res/CSS/style.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/Res/CSS/stylelog.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("javascript:window.history.forward(-1);\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");


String user = request.getParameter("userid");

UserDAO userDAO=UserDAO.getInstance();
String userName =userDAO.getName(userDAO.getID(user));



      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div \tstyle=\"position: centre;  left: -10px;\"\t>\r\n");
      out.write("<img alt=\"\" src=\"");
      out.print(request.getContextPath());
      out.write("/Res/Images/top.png\" height=\"100px\" width=100%\">\r\n");
      out.write("</img>\r\n");
      out.write("</div>\r\n");
      out.write("\t<div style=\"color: #2A0A0A;position:absolute;top:120px;left:800px;font-family: Monotype Corsiva;font-size: 20px;font-style: bold\"> Welcome[");
      out.print(userName );
      out.write("]</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"example\">\r\n");
      out.write("    <ul id=\"nav\">\r\n");
      out.write("        <li class=\"current\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/Res/JSP/User/userhome.jsp?userid=");
      out.print(user);
      out.write("\"  >Home</a></li>\r\n");
      out.write("        <li class=\"current\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/Res/JSP/User/uploadfile.jsp\" target=\"myIframe\">Upload </a>\r\n");
      out.write("            \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"current\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/Res/JSP/User/download.jsp\" target=\"myIframe\">Download/View </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"current\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/Res/JSP/User/view_deleted_fls.jsp\" target=\"myIframe\">Migrated Files</a></li>\r\n");
      out.write("        \r\n");
      out.write("        <li class=\"current\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/ChangePass1?name=");
      out.print(user);
      out.write("&no=1&id=");
      out.print(user );
      out.write("\" target=\"myIframe\">Change Password</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li class=\"current\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/index1.jsp?no=4\">Logout</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<div style=\"position:absolute;top:200px;left:100px;\">\r\n");
      out.write("\t<iframe align=\"middle\" src=\"");
      out.print(request.getContextPath() );
      out.write("/Res/JSP/User/usercontent.jsp\" frameborder=\"1\" scrolling=\"auto\" name=\"myIframe\" height=\"450\" width=\"800\" ></iframe>\r\n");
      out.write("</div>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
