/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2016-04-18 05:11:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Res.JSP.User;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.DAO.*;
import com.helperclass.*;

public final class users_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
public int convert(String str) 
{ 
	int conv=0; 
	if(str==null) 
	{ 
		str="0"; 
	} 
	else if((str.trim()).equals("null")) 
	{ 
		str="0"; 
	} 
	else if(str.equals("")) 
	{ 
		str="0"; 
	} 
	try
	{ 
		conv=Integer.parseInt(str); 
	} 
	catch(Exception e) 
	{ 
	} 
	return conv; 
	} 

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/Res/CSS/style1.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");

UserDAO userDAO = UserDAO.getInstance();

ResultSet rs = userDAO.getUsers();


      out.write("\r\n");
      out.write("<br></br>\r\n");
      out.write("<div class=\"CSSTableGenerator\" style=\"width:600px;height:150px;\">\r\n");
      out.write("<table class=\"pretty-table\">\r\n");
      out.write("  \r\n");
      out.write("    <th scope=\"col\">User No</th>\r\n");
      out.write("    <th scope=\"col\">User ID</th>\r\n");
      out.write("    <th scope=\"col\">User Name</th>\r\n");
      out.write("    <th scope=\"col\">User City</th>\r\n");
      out.write("    <th scope=\"col\">User Email</th>\r\n");
      out.write("    <th scope=\"col\">Edit</th>\r\n");
      out.write("    <th scope=\"col\">Delete</th>\r\n");
      out.write("  \r\n");
while(rs.next())
	{
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>");
      out.print(rs.getInt(1) );
      out.write("</td>\r\n");
      out.write("    \t<td>");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("    \t<td>");
      out.print(rs.getString(4) );
      out.write("</td>\r\n");
      out.write("    \t<td>");
      out.print(rs.getString(5) );
      out.write("</td>\r\n");
      out.write("    \t<td>");
      out.print(rs.getString(6) );
      out.write("</td>\r\n");
      out.write("    \t<td><a href=\"");
      out.print(request.getContextPath());
      out.write("/Res/JSP/Admin/edituser.jsp?code=");
      out.print(rs.getInt(1));
      out.write("&id=");
      out.print(rs.getString(2));
      out.write("&name=");
      out.print(rs.getString(4));
      out.write("&city=");
      out.print(rs.getString(5) );
      out.write("&mobile=");
      out.print(rs.getString(6));
      out.write("&submit=Edit\"><font style=\"color: blue;\"><b>Edit</b></font></a></td>\r\n");
      out.write("    \t<td><a href=\"");
      out.print(request.getContextPath());
      out.write("/EditUser?submit=Delete&chk=");
      out.print(rs.getInt(1) );
      out.write("\"><font style=\"color: blue;\"><b>Delete</b></font></a></td>\r\n");
      out.write("  </tr>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
	
		int no=Utility.parse(request.getParameter("no"));
System.out.println("No :"+no);
		if(no==1)
		{
      out.write("\r\n");
      out.write("\t\t<div  style=\"position: absolute;top: -10px;left: 50px;color: #000;font-size: 20px;font-family: monotype corsiva; \">\r\n");
      out.write("\t\t<p>User Details Updated Successfully..</p>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t");
}
		if(no==2)
		{
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div  style=\"position: absolute;top: -10px;left: 50px;color: #000;font-size: 20px; \">\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<p>User Deleted Successfully</p>\t\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t");
}
		
		
	
      out.write("\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
