/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2016-04-18 05:34:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Res.JSP.User;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.DAO.*;
import com.helperclass.*;

public final class view_005fdeleted_005ffls_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
public int convert(String str) 
{ 
	int conv=0; 
	if(str==null) 
	{ 
		str="0"; 
	} 
	else if((str.trim()).equals("null")) 
	{ 
		str="0"; 
	} 
	else if(str.equals("")) 
	{ 
		str="0"; 
	} 
	try
	{ 
		conv=Integer.parseInt(str); 
	} 
	catch(Exception e) 
	{ 
	} 
	return conv; 
	} 

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/Res/CSS/style1.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");

String userid = session.getAttribute("name").toString();
ResultSet rs = AdminDAO.getdeletedFiles(userid);





      out.write("\r\n");
      out.write("<br></br>\r\n");
      out.write("<div class=\"CSSTableGenerator\" style=\"width:600px;height:150px;\">\r\n");
      out.write("<table class=\"pretty-table\">\r\n");
      out.write("  \r\n");
      out.write("    <th scope=\"col\">File No</th>\r\n");
      out.write("    <th scope=\"col\">File Name</th>\r\n");
      out.write("    <th scope=\"col\">M Id</th>\r\n");
      out.write("    <th scope=\"col\">Data and Time</th>\r\n");
      out.write("    <th scope=\"col\">Status</th>\r\n");
      out.write("    <th scope=\"col\">Recovery</th>\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
while(rs.next())
	{
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>");
      out.print(rs.getInt(1) );
      out.write("</td>\r\n");
      out.write("    \t<td>");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("    \t<td>");
      out.print(rs.getString(3) );
      out.write("</td>\r\n");
      out.write("    \t<td>");
      out.print(rs.getString(4) );
      out.write("</td>\r\n");
      out.write("    \t<td>");
      out.print(rs.getString(5) );
      out.write("</td>\r\n");
      out.write("    \t");
if(rs.getString(5).equals("Approved")) 
    	{
      out.write("\r\n");
      out.write("    \t<td>File Recovered</td>\r\n");
      out.write("    \t");
} 
    	else 
    	{
      out.write("\r\n");
      out.write("    \t<td><a href=\"");
      out.print(request.getContextPath());
      out.write("/Res/JSP/User/request_recovery.jsp?fname=");
      out.print(rs.getString(2));
      out.write("&mid=");
      out.print(rs.getString(3));
      out.write("\">Req for Recovery</a></td>\r\n");
      out.write("    \t");
} 
      out.write("\r\n");
      out.write("    \t\r\n");
      out.write(" \r\n");
      out.write("  </tr>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");

	if(Utility.parse(request.getParameter("no"))==1)
    {
      out.write("\r\n");
      out.write("    \t<div class=\"success\" id=\"message\" style=\"position:absolute;top:-10px;font-size: 20px;color:#000;font-family: monotype corsiva;\">\t\r\n");
      out.write("    \t\t<p>Request have Send Successfully.....!</p>\r\n");
      out.write("    \t</div>\t\t\t\r\n");
      out.write("    ");
}
	if(Utility.parse(request.getParameter("no"))==2)
	{
      out.write("\r\n");
      out.write("\t\t<div class=\"success\" id=\"message\" style=\"position:absolute;top:-10px;font-size: 20px;color: #000;font-family: monotype corsiva;\">\t\r\n");
      out.write("\t\t\t<p>Opp's something went wrong.....!</p>\r\n");
      out.write("\t\t</div>\t\t\t\r\n");
      out.write("\t");

	}
	
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
