/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2016-05-03 08:05:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
public int convert(String str) 
{ 
	int conv=0; 
	if(str==null) 
	{ 
		str="0"; 
	} 
	else if((str.trim()).equals("null")) 
	{ 
		str="0"; 
	} 
	else if(str.equals("")) 
	{ 
		str="0"; 
	} 
	try
	{ 
		conv=Integer.parseInt(str); 
	} 
	catch(Exception e) 
	{ 
	} 
	return conv; 
	} 

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head><title>Cloud_SaDas</title>\r\n");
      out.write("<script type = \"text/javascript\">\r\n");
      out.write("function hideMessage()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"message\").style.display=\"none\"; \r\n");
      out.write("}\r\n");
      out.write("function startTimer() \r\n");
      out.write("{\r\n");
      out.write("\tvar tim = window.setTimeout(\"hideMessage()\", 2000);  // 5000 milliseconds = 5 seconds\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#amutha\r\n");
      out.write("{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\ttop: 150px;\r\n");
      out.write("\tleft:520px;\r\n");
      out.write("\tbackground:#606060;\r\n");
      out.write("\tcolor:#fff;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\twidth:500px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/Res/CSS/stylelog.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/Res/CSS/message.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
int no=convert(request.getParameter("no"));
if(no==1)
{
      out.write("\r\n");
      out.write("<div id=\"amutha\">\r\n");
      out.write("\t<p id=\"message\">Opp's.......Please enter your userid</p>\r\n");
      out.write("</div>\r\n");
}if(no==2)
{
      out.write("\r\n");
      out.write("<div id=\"amutha\">\r\n");
      out.write("\t<p id=\"message\">Opp's.......Please enter your password</p>\r\n");
      out.write("</div>\r\n");
}
      out.write('\r');
      out.write('\n');
if(no==3)
{
      out.write("\r\n");
      out.write("<div id=\"amutha\">\r\n");
      out.write("\t<p id=\"message\">Opp's.......invalid username/password...!</p>\r\n");
      out.write("</div>\r\n");
}
      out.write('\r');
      out.write('\n');
if(no==4)
{
      out.write("\r\n");
      out.write("<div id=\"amutha\">\r\n");
      out.write("\t<p id=\"message\">You have Logged out successfully...!</p>\r\n");
      out.write("</div>\r\n");
}
      out.write('\r');
      out.write('\n');
if(no==5)
{
      out.write("\r\n");
      out.write("<div id=\"amutha\">\r\n");
      out.write("\t<p id=\"message\">User Registered Successfully...!</p>\r\n");
      out.write("</div>\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div \tstyle=\"position: centre;  left: -10px;\"\t>\r\n");
      out.write("<img alt=\"\" src=\"");
      out.print(request.getContextPath());
      out.write("/Res/Images/top.png\" height=\"100px\" width=100%\">\r\n");
      out.write("</img>\r\n");
      out.write("</div>\r\n");
      out.write("<form id=\"login\" action=\"");
      out.print(request.getContextPath());
      out.write("/UserLogin\" method=\"post\">\r\n");
      out.write("    <h1 id=\"ff-proof\" class=\"ribbon\">User Login &nbsp;&nbsp;</h1>\r\n");
      out.write("    \r\n");
      out.write("    <fieldset id=\"inputs\">\r\n");
      out.write("        <input id=\"username\" type=\"text\" name=\"username\" onblur=\"if(this.value=='')this.value='user name';\" onfocus=\"if(this.value=='user name')this.value='';\"  required=\"yes\" />\r\n");
      out.write("        <input id=\"password\" type=\"password\" name=\"pass\" onblur=\"if(this.value=='')this.value='user password';\" onfocus=\"if(this.value=='user password')this.value='';\" required=\"yes\"  />\r\n");
      out.write("    </fieldset>\r\n");
      out.write("    <fieldset id=\"actions\">\r\n");
      out.write("        <input type=\"submit\" id=\"submit\" value=\"Login\"/>\r\n");
      out.write("       <p class=\"option\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/index.jsp\">Admin</a>&nbsp;&nbsp;|<a href=\"");
      out.print(request.getContextPath());
      out.write("/index1.jsp\">User</a></p>\r\n");
      out.write("    </fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
